"""Update interests to list

Revision ID: 2792b3b27abc
Revises: 20260808_0001
Create Date: 2026-08-10 03:32:24.649036
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2792b3b27abc'
down_revision: str | None = '20260808_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
