"""Add ScheduledTask and NotificationHistory

Revision ID: d31b19aa34e6
Revises: 2792b3b27abc
Create Date: 2026-08-10 10:10:48.084425
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd31b19aa34e6'
down_revision: str | None = '2792b3b27abc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_key', name='uq_notification_user_event')
    )
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_next_run_at'), 'scheduled_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_user_id'), 'scheduled_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_tasks_user_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_next_run_at'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
